class Mensajes:
    mensajes_es = {
        "welcome_menu": "\nBienvenido a Petshop \nSeleccione la opción deseada: \n\n1. Generar datos ficticios.\n2. Generar datos ficticios desde un txt.\n3. Usuarios.\n4. Salir.",
        "user_type": "\nSeleccione el tipo de usuario: \n\n1. Cliente.\n2. Empleado.\n3. Volver al menu principal.",
        "client_login_menu": "\nSelecciona una opcion\n\n1. Iniciar sesión.\n2. Registrarse.\n3. Volver al menu principal.",
        "succes_dummy_data": "\n----------------------------------------\nLos datos han sido añadidos con exito.\n----------------------------------------",
        "dummy_data_added": "\n----------------------------------------\nERROR\nYa agrego datos ficticios con anterioridad.\n----------------------------------------",
        "ID": "ID: ",
        "user_id": "\nIdentificación: ",
        "user_name": "\nNombre: ",
        "user_phone": "\nTelefono: ",
        "user_address": "\nDireccion: ",
        "user_password": "\nContraseña: ",
        "user_active": "\nActivo: ",
        "email": "\nCorreo electrónico: ",
        "password": "Contraseña: ",
        "value": "\nPrecio: ",
        "amount": "\nCantidad: ",
        "description" : "\nDescripcion: ",
        "details": "\n\nDetalles: ",
        "comments": "\n\nComentarios: ",
        "amount_inventory": "\nCantidad en inventario: ",
        "date": "\nFecha: ",
        "state": "\nEstado del pedido: ",
        "error_login": "\n----------------------------------------\nERROR\nNo se pudo encontrar su direccion de correo electronico en el sistema.\n----------------------------------------",
        "error_register": "\n----------------------------------------\nERROR\nAlguien ya se ha registrado con ese email.\n----------------------------------------",
        "succes_login": "\n----------------------------------------\nHa iniciado sesion con exito.\n----------------------------------------",
        "succes_register": "\n----------------------------------------\nSe ha registrado con exito.\n----------------------------------------",
        "employee_login_menu": "\nSelecciona una opcion\n\n1. Iniciar sesión.\n2. Volver al menu principal.",
        "client_menu": ", Bienvenido a PetShop, ¿Que desea hacer?\n\n1. Ver productos. \n2. Seleccionar producto(s). \n3. Crear comentario. \n4. Ver carrito de compras.  \n5. Ver lista de deseos. \n6. Ver mis pedidos realizados. \n7. Desconectarme.",
        "employee_menu": "\n1. Crear productos. \n2. Buscar productos. \n3. Actualizar producto. \n4. Eliminar producto. \n5. Anular pedidos. \n6. Ver pedidos del día. \n7. Ver promedio ventas del día. \n8. Desconectarse.",
        "admin_menu": "\n1. Crear administrador. \n2. Crear empleados. \n3. Desactivar o activar empleado. \n4. Crear productos. \n5. Buscar productos. \n6. Actualizar producto. \n7. Eliminar producto. \n8. Anular pedidos. \n9. Ver pedidos del día. \n10. Ver promedio ventas del día. \n11. Desconectarse.",
        "wrong_option": "\n----------------------------------------\nERROR\nOpción inválida. Por favor digite su seleccion nuevamente.\n----------------------------------------",
        "empl_exists": "Ya existe un empleado con este correo electrónico, por favor intente con uno diferente.",
        "empl_added": "\n----------------------------------------\nEl empleado fue creado exitosamente.\n----------------------------------------",
        "insert_product_id": "\nIngrese el ID del producto a buscar: ",
        "insert_product_id_select": "\nIngrese el ID del producto a seleccionar: ",
        "insert_product_id_update": "\nIngrese el ID del producto a actualizar: ",
        "insert_product_id_delete": "\nIngrese el ID del producto a eliminar: ",
        "select_product_menu" : "\n¿Que desea hacer con el producto que acaba de seleccionar?\n\n1. Agregar a lista de deseados.\n2. Agregar a carrito de compras.\n3. Salir.",
        "product_not_found": "\n----------------------------------------\nProducto(s) no encontrado(s).\n----------------------------------------",
        "product_sold_out": "\nLa cantidad en inventario es menor a la solicitada, por favor intente nuevamente. \nProductos en inventario: ",
        "go_back_press_any_key": "\nPara volver atras presione cualquier tecla: ",
        "wish_list": "\n------------------------------------------\nLista de deseos.\n------------------------------------------",
        "enter_data_employee": "\n----------------------------------\nPor favor ingrese los datos del empleado.\n----------------------------------",
        "enter_product_info": "\nIngrese la información del producto: ",
        "product_added": "\n----------------------------------------\nProducto añadido con exito.\n----------------------------------------",
        "product_with_same_name": "\n----------------------------------------\nERROR\nYa hay un producto con ese mismo nombre.\n----------------------------------------",
        "product_already_added": "\n----------------------------------------\nERROR\nYa existe este producto en su lista de deseos.\n----------------------------------------",
        "product_to_search": "\nIngrese el nombre de los productos a buscar: ",
        "product_deleted": "\n----------------------------------\nProducto borrado con exito.\n----------------------------------",
        "product_updated": "\n----------------------------------\nProducto actualizado con exito.\n----------------------------------",
        "insert_employee_id": "\nIngrese el ID del empleado a desactivar o activar: ",
        "insert_employee_id_delete": "\nIngrese el ID del empleado a eliminar: ",
        "deactivate_confirmation": "\n----------------------------------\nEl empleado fue desactivado exitosamente.\n----------------------------------",
        "activate_confirmation": "\n----------------------------------\nEl empleado fue activado exitosamente.\n----------------------------------",
        "deactivated_employee": "\nEste empleado no tiene acceso a Petshop en este momento.",
        "delete_employee_confirmation": "\nEste empleado fue eliminado exitosamente.",
        "employee_not_found": "\nNo existe un empleado con este ID, por favor intente nuevamente.",
        "success_cart_add": "\n----------------------------------------\nAgregado exitosamente a carrito de compras.\n----------------------------------------",
        "product_already_added_carrito": "\n----------------------------------------\nERROR\nYa existe este producto en su carrito de compras.\n----------------------------------------",
        "wish_list_carrito": "\n-------------------------------------------------\nCarrito de Compras:\n-------------------------------------------------",
        "make_order": "\n1. Realizar Pedido.\n2. Borrar producto.",
        "product_quantity": "\n¿Cuántas unidades del producto desea agregar al carrito?",
        "subtotal": "\nSubtotal: ",
        "order_total_value": "\nTotal: ",
        "buy_menu": "\n¿Que desea hacer?\n\n1. Comprar.\n2. Retirar producto del carrito.\n3. Volver atras.",
        "previous_orders": "\n-------------------------------------------------\nPedidos anteriores.\n-------------------------------------------------",
        "order_number": "Pedido #",
        "order_successfully": "\n----------------------------------------\nCompra realizada con exito.\n----------------------------------------",
        "empty_shopping_cart": "\n----------------------------------------\nERROR\nNo hay productos en tu carrito de compras.\n----------------------------------------",
        "order_not_found": "\n----------------------------------------\nERROR\nNo has realizado pedidos con anterioridad.\n----------------------------------------",
        "id_order_to_cancel": "\nIngrese el id del pedido a anular: ",
        "order_successfully_cancel": "\n----------------------------------------\nPedido cancelado con exito.\n----------------------------------------",
        "order_to_cancel_not_found": "\n----------------------------------------\nERROR\nNo se encontraron pedidos con esa Id.\n----------------------------------------",
        "autor": "\nHecho por: ",
        "id_to_comment": "\nIngrese el Id del producto a Comentar: ",
        "the_comment": "\nIngrese el Comentario: ",
        "wish_list_menu": "\n¿Que desea hacer?\n\n1. Comprar.\n2. Eliminar productos de mi lista de deseados.\n3. Salir al menu.",
        "product_not_found_in_wish_list": "\n----------------------------------------\nERROR\nProducto no encontrado en lista deseados.\n----------------------------------------",
        "insert_product_id_buy": "\n Inserte el ID del producto a comprar.\n",
        "empty_wish_list": "\n----------------------------------------\nERROR\nLista de deseos vacia.\n----------------------------------------",
        "average_sales": "\nEl valor promedio de las ventas del día fue $ ",
        "total_sales": "\nEl valor total de las ventas del dia fue $ ",
        "no_orders_day": "\n----------------------------------------\nERROR\nNo hay pedidos para el día de hoy.\n----------------------------------------"
    }

    mensajes_eng = {
        "welcome_menu": "\nWelcome to Petshop \nSelect the desired option: \n\n1. Generate dummy data. \n2. Generate dummy data from a txt file. \n3. Users. \n4. Exit.",
        "user_type": "\nSelect the user type: \n\n1. Client. \n2. Employee. \n3. Go to the start menu.",
        "client_login_menu": "\nSelect the user option\n\n1. Login. \n2. Sign up. \n3. Go back.",
        "succes_dummy_data": "\n----------------------------------------\nData added successfully.\n----------------------------------------",
        "dummy_data_added": "\n----------------------------------------\nERROR\nYou already added dummy data.\n----------------------------------------",
        "user_id": "\nId: ",
        "ID": "ID: ",
        "user_name": "\nName: ",
        "user_phone": "\nPhone number: ",
        "user_address": "\nAddress: ",
        "user_password": "\nPassword: ",
        "user_active": "\nActive: ",
        "email": "\nEmail: ",
        "password": "Password: ",
        "value": "\nPrice: ",
        "amount": "\nAmount: ",
        "description": "\nDescription: ",
        "details": "\n\nDetails: ",
        "comments": "\n\nComments: ",
        "amount_inventory": "\nAmount on inventory: ",
        "date": "\nDate: ",
        "state": "\nState of the order: ",
        "error_login": "\n----------------------------------------\nERROR\nWe can't find your email in our database.\n----------------------------------------",
        "error_register": "\n----------------------------------------\nERROR\nSomeone already took your email.\n----------------------------------------",
        "succes_login": "\n----------------------------------------\nYou have logged in successfully.\n----------------------------------------",
        "succes_register": "\n----------------------------------------\nYou have registered successfully.\n----------------------------------------",
        "employee_login_menu": "\nSelect the employee option\n\n1. Login.\n2. Go to the start menu.",
        "client_menu": ", Welcome to PetShop, What do you want to do?\n\n1. See products. \n2. Select product(s). \n3. Create comment. \n4. See my shopping cart. \n5. See my wish list. \n6. See my previous orders. \n7. Logout.",
        "employee_menu": "\n1. Create product \n2. Search products \n3. Update product \n4. Delete product \n5. Cancel order \n6. See orders of the day \n7. Logout",
        "admin_menu": "\n1. Create administrator. \n2. Create employee. \n3. Deactivate or activate employee. \n4. Create product. \n5. Search products. \n6. Update product. \n7. Delete product. \n8. Cancel order. \n9. See orders of the day. \n10. Logout.",
        "wrong_option": "\n----------------------------------------\nERROR\nWrong option. Please enter a valid option.\n----------------------------------------",
        "empl_exists": "\n----------------------------------------\nERROR\nAn employee with this email already exists, please try again.\n----------------------------------------",
        "empl_added": "\n----------------------------------------\nThe employee was created successfully.\n----------------------------------------",
        "insert_product_id": "\nInsert the product ID: ",
        "insert_product_id_select": "\nInsert the ID for the product to select: ",
        "insert_product_id_update": "\nInsert the ID for the product to update: ",
        "insert_product_id_delete": "\nInsert the ID for the product to delete: ",
        "select_product_menu": "\nWhat you want to do with the selected product?\n\n1. Add to wish list.\n2. Add to shopping cart.\n3. Exit.",
        "product_not_found": "\n----------------------------------------\nProduct(s) not found.\n----------------------------------------",
        "product_sold_out": "\nProduct quantity in stock is less than the requested amount. \nProducts in stock: ",
        "go_back_press_any_key": "\nTo go back press any key: ",
        "wish_list": "\n----------------------------------------\nWish list.\n----------------------------------------",
        "enter_data_employee": "\n----------------------------------\nPlease enter the employee information.\n----------------------------------",
        "enter_product_info": "\nEnter the information of the product: ",
        "product_added": "\n----------------------------------------\nProduct succesfully added.\n----------------------------------------",
        "product_with_same_name": "\n----------------------------------------\nERROR\nThere's a product with the same name.\n----------------------------------------",
        "product_already_added": "\n----------------------------------------\nERROR\nThis product is already in your wish list.\n----------------------------------------",
        "product_to_search": "\nEnter the name of the product to search: ",
        "product_deleted": "\n----------------------------------\nProduct successfully deleted.\n----------------------------------",
        "product_updated": "\n----------------------------------\nProduct successfully updated.\n----------------------------------",
        "insert_employee_id": "\nPlease enter the ID for the employee to activate or deactivate: ",
        "insert_employee_id_delete": "\nPlease enter the ID for the employee to delete: ",
        "deactivate_confirmation": "\n----------------------------------\nThe employee was deactivated successfully.\n----------------------------------",
        "activate_confirmation": "\n----------------------------------\nThe employee was activated successfully.\n----------------------------------",
        "deactivated_employee": "\nThis employee has no access to Petshop at this moment.",
        "delete_employee_confirmation": "\nThis employee was deleted successfully.",
        "employee_not_found": "\nAn employee with this ID does not exist. Please try again.",
        "success_cart_add": "\n Successfully added to your shopping cart",
        "product_already_added_carrito": "\n----------------------------------------\nERROR\nThis product is already added to your shopping car.\n----------------------------------------",
        "wish_list_carrito": "\n-------------------------------------------------\nShopping Car:\n-------------------------------------------------",
        "make_order": "\n1. Make order \n2. Delete product.",
        "product_quantity": "\n How many unities of the product would you like?",
        "subtotal": "\nSubtotal: ",
        "order_total_value": "\nTotal: ",
        "buy_menu": "\nWhat do you want to do?\n\n1. Buy.\n2. Remove product from shopping cart.\n3. Go back.",
        "previous_orders": "\n-------------------------------------------------\nPrevious orders.\n-------------------------------------------------",
        "order_number": "Order #",
        "order_successfully": "\n----------------------------------------\nCompleted purchase.\n----------------------------------------",
        "empty_shopping_cart":"\n----------------------------------------\nERROR\nThere's no products in your shopping cart.\n----------------------------------------",
        "order_not_found": "\n----------------------------------------\nERROR\nYou haven't previous orders.\n----------------------------------------",
        "id_order_to_cancel": "\nEnter id of the order to cancel: ",
        "order_successfully_cancel": "\n----------------------------------------\nOrder successfully canceled.\n----------------------------------------",
        "order_to_cancel_not_found": "\n----------------------------------------\nERROR\nThere's no orders with that Id.\n----------------------------------------",
        "autor": "\nMade by: ",
        "id_to_comment": "\nPlease enter the id of the product you want to comment: ",
        "the_comment": "\nMake a comment: ",
        "wish_list_menu": "\nWhat would you like to do?\n\n1. Buy.\n2. Delete products of my wish list.\n3. Go to main menu.",
        "product_not_found_in_wish_list": "\n----------------------------------------\nERROR\nProduct not found in wish list.\n----------------------------------------",
        "insert_product_id_buy": "\n Insert the id of the product you want to buy.\n",
        "empty_wish_list": "\n----------------------------------------\nERROR\nEmpty wish list.\n----------------------------------------",
        "average_sales": "\nThe average value for the day sales was $ ",
        "total_sales": "\nThe total value for the day sales was $ ",
        "no_orders_day": "\n----------------------------------------\nERROR\nThere are not orders for today.\n----------------------------------------"
    }
