class Mensajes:
    mensajes_es = {
        "welcome_menu": "\nBienvenido a Petshop \nSeleccione la opción deseada: \n\n1. Generar datos ficticios \n2. Generar datos ficticios desde un txt \n3. Usuarios \n4. Salir",
        "user_type": "\nSeleccione el tipo de usuario: \n\n1. Cliente \n2. Empleado \n3. Volver al menu principal",
        "client_login_menu": "\nSelecciona una opcion\n\n1. Iniciar sesión \n2. Registrarse \n3. Volver al menu principal",
        "succes_dummy_data": "\nLos datos han sido añadidos con exito",
        "dummy_data_added": "\n----------------------------------------\nERROR\nYa agrego datos ficticios con anterioridad\n----------------------------------------",
        "ID": "\nID: ",
        "user_id": "\nIdentificación: ",
        "user_name": "\nNombre: ",
        "user_phone": "\nTelefono: ",
        "user_address": "\nDireccion: ",
        "user_password": "\nContraseña: ",
        "user_active": "\nActivo: ",
        "email": "\nCorreo electrónico: ",
        "password": "Contraseña: ",
        "value": "\nPrecio: ",
        "description" : "\nDescripcion: ",
        "amount_inventory": "\nCantidad en inventario: ",
        "error_login": "\n----------------------------------------\nERROR\nNo se pudo encontrar su direccion de correo electronico en el sistema\n----------------------------------------",
        "error_register": "\n----------------------------------------\nERROR\nAlguien ya se ha registrado con ese email\n----------------------------------------",
        "succes_login": "\n----------------------------------------\nHa iniciado sesion con exito\n----------------------------------------",
        "succes_register": "\n----------------------------------------\nSe ha registrado con exito\n----------------------------------------",
        "employee_login_menu": "\n1.Iniciar sesión\n2. Volver al menu principal",
        "client_menu": ", Bienvenido a PetShop, ¿Que desea hacer?\n\n1. Ver productos \n2. Seleccionar producto(s) \n3. Borrar comentario \n4. Ver carrito de compras  \n5. Ver lista de deseos \n6. Ver mis pedidos realizados \n7. Desconectarme",
        "employee_menu": "1. Crear productos \n2. Buscar productos \n3. Actualizar producto \n4. Eliminar producto \n5. Anular pedidos \n6. Ver pedidos del día \n7. Desconectarse",
        "admin_menu": "1. Crear administrador \n2. Crear empleados \n3. Desactivar o activar empleado \n4. Crear productos \n5. Buscar productos \n6. Actualizar producto \n7. Eliminar producto \n8. Anular pedidos \n9. Ver pedidos del día \n10. Desconectarse",
        "wrong_option": "\n----------------------------------------\nERROR\nOpción inválida. Por favor digite su seleccion nuevamente\n----------------------------------------",
        "empl_exists": "Ya existe un empleado con este correo electrónico, por favor intente con uno diferente.",
        "empl_added": "El empleado fue creado exitosamente.",
        "insert_product_id": "\nIngrese el ID del producto a buscar: ",
        "select_product_menu" : "\n¿Que desea hacer con el producto que acaba de seleccionar?\n\n1. Agregar a lista de deseados\n2. Comprar\n3. Salir",
        "product_not_found": "\n----------------------------------------\nProducto(s) no encontrado(s)\n----------------------------------------",
        "go_back_press_any_key": "\nPara volver atras presione cualquier tecla: ",
        "wish_list": "\n------------------------------------------\nLista de deseos\n------------------------------------------",
        "enter_data_employee": "\n----------------------------------\nPor favor ingrese los datos del empleado\n----------------------------------",
        "enter_product_info": "\nIngrese la información del producto: ",
        "product_added": "\n----------------------------------------\nProducto añadido con exito\n----------------------------------------",
        "product_with_same_name": "\n----------------------------------------\nERROR\nYa hay un producto con ese mismo nombre\n----------------------------------------",
        "product_already_added": "\n----------------------------------------\nERROR\nYa existe este producto en su lista de deseos\n----------------------------------------",
        "product_to_search": "\nIngrese el nombre de los productos a buscar: ",
        "product_deleted": "\n----------------------------------\nProducto borrado con exito\n----------------------------------",
        "product_updated": "\n----------------------------------\nProducto actualizado con exito\n----------------------------------",
        "insert_employee_id": "\nIngrese el ID del empleado a desactivar o activar: ",
        "insert_employee_id_delete": "\nIngrese el ID del empleado a eliminar: ",
        "deactivate_confirmation": "\nEl empleado fue desactivado exitosamente.",
        "activate_confirmation": "\nEl empleado fue activado exitosamente.",
        "deactivated_employee": "\nEste empleado no tiene acceso a Petshop en este momento.",
        "delete_employee_confirmation": "\nEste empleado fue eliminado exitosamente.",
        "employee_not_found": "\nNo existe un empleado con este ID, por favor intente nuevamente.",
        "success_add": "\n----------------------------------------\nAgregado exitosamente a Carrito de Compras\n----------------------------------------",
        "product_already_added_carrito": "\n----------------------------------------\nERROR\nYa existe este producto en su carrito de compras\n----------------------------------------",
        "wish_list_carrito": "\n------------------------------------------\nCarrito de Compras:\n------------------------------------------"
    }

    mensajes_eng = {
        "welcome_menu": "\nWelcome to Petshop \nSelect the desired option: \n1. Generate dummy data \n2. Generate dummy data from a txt file \n3. Users \n4. Exit",
        "user_type": "\nSelect the user type: \n\n1. Client \n2. Employee \n3. Go to the start menu",
        "client_login_menu": "\nSelect the user option: \n\n1. Login \n2. Sign up \n3. Go back",
        "succes_dummy_data": "\nData added successfully",
        "dummy_data_added": "\n----------------------------------------\nERROR\nYou already added dummy data\n----------------------------------------",
        "user_id": "\nId: ",
        "ID": "\nID: ",
        "user_name": "\nName: ",
        "user_phone": "\nPhone number: ",
        "user_address": "\nAddress: ",
        "user_password": "\nPassword: ",
        "user_active": "\nActive: ",
        "email": "\nEmail: ",
        "password": "Password: ",
        "value": "\nPrice: ",
        "description": "\nDescription: ",
        "amount_inventory": "\nAmount on inventory: ",
        "error_login": "\n----------------------------------------\nERROR\nWe can't find your email in our database\n----------------------------------------",
        "error_register": "\n----------------------------------------\nERROR\nSomeone already took your email\n----------------------------------------",
        "succes_login": "\n----------------------------------------\nYou have logged in successfully\n----------------------------------------",
        "succes_register": "\n----------------------------------------\nYou have registered successfully\n----------------------------------------",
        "employee_login_menu": "\n1.Login\n2. Go to the start menu",
        "client_menu": ", Welcome to PetShop, What do you want to do?\n\n1. See products \n2. Select product(s) \n3. Delete comment \n4. See shopping car \n5. See wish list \n6. See my previous orders \n7. Logout",
        "employee_menu": "1. Create product \n2. Search products \n3. Update product \n4. Delete product \n5. Cancel order \n6. See orders of the day \n7. Logout",
        "admin_menu": "1. Create administrator \n2. Create employee \n3. Deactivate or activate employee \n4. Create product \n5. Search products \n6. Update product \n7. Delete product \n8. Cancel order \n9. See orders of the day \n10. Logout",
        "wrong_option": "\n----------------------------------------\nERROR\nWrong option. Please enter a valid option\n----------------------------------------",
        "empl_exists": "\n----------------------------------------\nERROR\nAn employee with this email already exists, please try again.\n----------------------------------------",
        "empl_added": "\n----------------------------------------\nThe employee was created successfully.\n----------------------------------------",
        "insert_product_id": "\nInsert the product ID: ",
        "select_product_menu": "\nWhat you want to do with the selected product?\n\n1. Add to wish list\n2. Buy\n3. Exit",
        "product_not_found": "\n----------------------------------------\nProduct(s) not found\n----------------------------------------",
        "go_back_press_any_key": "\nTo go back press any key: ",
        "wish_list": "\n----------------------------------------\nWish list\n----------------------------------------",
        "enter_data_employee": "\n----------------------------------\nPlease enter the employee information\n----------------------------------",
        "enter_product_info": "\nEnter the information of the product: ",
        "product_added": "\n----------------------------------------\nProduct succesfully added\n----------------------------------------",
        "product_with_same_name": "\n----------------------------------------\nERROR\nThere's a product with the same name\n----------------------------------------",
        "product_already_added": "\n----------------------------------------\nERROR\nThis product is already in your wish list\n----------------------------------------",
        "product_to_search": "\nEnter the name of the product to search: ",
        "product_deleted": "\n----------------------------------\nProduct successfully deleted\n----------------------------------",
        "product_updated": "\n----------------------------------\nProduct successfully updated\n----------------------------------",
        "insert_employee_id": "\nPlease enter the ID for the employee to activate or deactivate: ",
        "insert_employee_id_delete": "\nPlease enter the ID for the employee to delete: ",
        "deactivate_confirmation": "\nThe employee was deactivated successfully.",
        "activate_confirmation": "\nThe employee was activated successfully.",
        "deactivated_employee": "\nThis employee has no access to Petshop at this moment.",
        "delete_employee_confirmation": "\nThis employee was deleted successfully.",
        "employee_not_found": "\nAn employee with this ID does not exist. Please try again.",
        "success_add": "\n Successfully added to your shopping car",
        "product_already_added_carrito": "\n----------------------------------------\nERROR\nThis product is already added to your shopping car\n----------------------------------------",
        "wish_list_carrito": "\n------------------------------------------\nShopping Car:\n------------------------------------------"
    }
